---
- name: Attempting to generate temporary file
  tags: percona
  tempfile:
    prefix: percona.
    state: file
    suffix: .rpm
  register: percona_tempfile

- name: Attempting to download package to temporary location
  tags: percona
  get_url:
    dest: "{{ percona_tempfile.path }}"
    force: true
    url: "{{ percona_fetch }}"
  register: percona_get_url
  when: percona_tempfile is success

- name: Ensure that the {{ percona_pkg }} package is installed
  tags: percona
  become: true
  yum:
    name: "{{ percona_tempfile.path }}"
    state: present
  register: percona_yum
  when: percona_get_url is success

- name: Attempting to purge temporary package from the filesystem
  tags: percona
  file:
    path: "{{ percona_tempfile.path }}"
    state: absent
  when:
    - percona_tempfile is success
    - percona_yum is success

- name: Attempting to overlay percona repository configurations
  tags: percona
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: percona-release.repo.j2
      dst: /etc/yum.repos.d/percona-release.repo
  when: percona_yum is success

- name: Ensure that the percona gpg keys are installed
  tags: percona
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-Percona
    state: present
  when: percona_yum is success

- name: Ensure that the required percona packages are installed
  tags: percona
  become: true
  yum:
    disablerepo: "{{ percona_disablerepo|join(',') }}"
    enablerepo: "{{ percona_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  with_items: "{{ percona_packages }}"
  when:
    - percona_packages|length > 0
    - percona_yum is success
...
