---
- name: Assert that the prerequisites are defined
  tags: percona
  assert:
    that:
      - percona_pkg is defined
      - percona_ver is defined
      - percona_rel is defined
      - percona_baseurl is defined

- name: Generating temporary filename via mktemp
  tags: percona
  command: mktemp -u --suffix .rpm
  register: percona_mktemp

- name: Downloading package to temporary location
  tags: percona
  get_url:
    dest: "{{ percona_mktemp.stdout }}"
    url: "{{ percona_fetch }}"
  register: percona_get_url
  when: percona_mktemp|success

- name: Ensure that the percona-release package is installed
  tags: percona
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: percona_yum
  with_items: "{{ percona_mktemp.stdout }}"
  when: percona_get_url|success

- name: Applying percona-release.repo configurations
  tags: percona
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: percona-release.repo.j2, dst: /etc/yum.repos.d/percona-release.repo }
  when: percona_yum|success

- name: Ensure that the Percona GPG keys are installed
  tags: percona
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-Percona
    state: present

- name: Purging temporary package from filesystem
  tags: percona
  file:
    path: "{{ percona_mktemp.stdout }}"
    state: absent
  when:
    - percona_mktemp|success
    - percona_yum|success
...
